/// Sales targets loaded from Excel
table Targets

	partition 'Targets-Partition' = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\data\Targets.xlsx"), null, true),
				Sheet1 = Source{[Item="Targets",Kind="Sheet"]}[Data],
				PromotedHeaders = Table.PromoteHeaders(Sheet1, [PromoteAllScalars=true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"Region", type text}, {"Target", type number}})
			in
				ChangedTypes

	column Region
		dataType: string

	column Target
		dataType: double
		formatString: #,0.00
